## https://www.youtube.com/watch?v=2SDgIyrXmKc&ab_channel=mediumguy
## https://www.youtube.com/watch?v=Z0FtabDUPtU&ab_channel=MinIO
version: '3'
services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-03-15T01-07-19Z-cpuv1
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./minio-storage:/data
    command: server --console-address ":9090" /data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
#      MINIO_SERVER_URL: http://127.0.0.1:9000
    restart: always