spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  application:
    name: doctor-clinics
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/ORCLPDB
    username: DEMO
    password: demo
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  sql:
    init:
      mode: never
      continue-on-error: false

minio:
  bucket: doctor-clinics
  endpoint: http://127.0.0.1:9000
  accessKey: user
  secretKey: password